jwt.secret=capprezy
#************** DATABASE **************#
spring.datasource.url=jdbc:postgresql://ec2-176-34-237-141.eu-west-1.compute.amazonaws.com:5432/d2pl3hfrhi2ba1
spring.datasource.username=yqpxiwptlwitap
spring.datasource.password=8ecb0f3141946d4cb6eae86b08ed5c4a405dfeb4fefd01dab8a1b70424683f7b

spring.jpa.show-sql = true
spring.jpa.properties.hibernate.default_schema=caprezzy
spring.jpa.properties.connection.characterEncoding=utf-8
spring.jpa.properties.connection.CharSet=utf-8
spring.jpa.properties.connection.useUnicode=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQL10Dialect
#************** SECURITY **************#
server.servlet.session.timeout=60m